In [1]:
import torch

In [2]:
a = torch.rand(3,3)

In [3]:
a

tensor([[0.1389, 0.9769, 0.7235],
        [0.4571, 0.6830, 0.9278],
        [0.4218, 0.8408, 0.3321]])

In [4]:
b = torch.rand(19,19,1)

In [5]:
b

tensor([[[0.9889],
         [0.6535],
         [0.7963],
         [0.3315],
         [0.7211],
         [0.7292],
         [0.3621],
         [0.7106],
         [0.2087],
         [0.7872],
         [0.4230],
         [0.7987],
         [0.1181],
         [0.3092],
         [0.8879],
         [0.8868],
         [0.0809],
         [0.1499],
         [0.4937]],

        [[0.2787],
         [0.2256],
         [0.3013],
         [0.9232],
         [0.4064],
         [0.6082],
         [0.4477],
         [0.4175],
         [0.3505],
         [0.2799],
         [0.3729],
         [0.6939],
         [0.4647],
         [0.8051],
         [0.5150],
         [0.7931],
         [0.8299],
         [0.2904],
         [0.7359]],

        [[0.3943],
         [0.7663],
         [0.0910],
         [0.2729],
         [0.1506],
         [0.8631],
         [0.5861],
         [0.1140],
         [0.5955],
         [0.9223],
         [0.9040],
         [0.7706],
         [0.3636],
         [0.1014],
        

In [10]:
b[0][1] = 1
print(b[0][2])
b[0][1] + b[0][2]

tensor([0.7963])


tensor([1.7963])

In [2]:
scores = torch.rand(19,19,2,1)

In [16]:
s = torch.full_like(scores[:, :, 0], float('-inf'))

In [5]:
s.shape

torch.Size([19, 19, 1])

In [7]:
s2 = scores.new_zeros(19, 19, 1)
s2.shape

torch.Size([19, 19, 1])

In [9]:
seq_len = 19
batch_size = 1

In [10]:
p_s = scores.new_zeros(seq_len, seq_len, batch_size).long()
p_l = scores.new_zeros(seq_len, seq_len, batch_size).long()

In [11]:
for d in range(2, seq_len + 1):
    offset = d - 1
    n = seq_len - offset
    starts = p_s.new_tensor(range(n)).unsqueeze(0)
    # [batch_size, n]
    s_label, p_label = scores.diagonal(offset).max(0)
    p_l.diagonal(offset).copy_(p_label)

In [12]:
s

tensor([[[-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf]],

        [[-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf]],

        [[-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf]],

        [[-inf],
        

In [18]:
for i in range(seq_len):
    s[i,i] = 0

In [19]:
s

tensor([[[0.],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf]],

        [[-inf],
         [0.],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf]],

        [[-inf],
         [-inf],
         [0.],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf],
         [-inf]],

        [[-inf],
         [-inf

In [1]:
scores = [[[[0.0163],
          [0.0104]],

         [[0.0177],
          [0.0113]],

         [[0.0193],
          [0.0123]],

         [[0.0196],
          [0.0125]],

         [[0.0222],
          [0.0142]],

         [[0.0225],
          [0.0145]],

         [[0.0230],
          [0.0148]],

         [[0.0229],
          [0.0148]],

         [[0.0232],
          [0.0149]],

         [[0.0234],
          [0.0150]],

         [[0.0236],
          [0.0151]],

         [[0.0232],
          [0.0149]],

         [[0.0228],
          [0.0146]],

         [[0.0219],
          [0.0140]],

         [[0.0210],
          [0.0134]],

         [[0.0190],
          [0.0121]],

         [[0.0168],
          [0.0106]]],


        [[[0.0193],
          [0.0108]],

         [[0.0210],
          [0.0118]],

         [[0.0229],
          [0.0128]],

         [[0.0232],
          [0.0131]],

         [[0.0264],
          [0.0148]],

         [[0.0268],
          [0.0151]],

         [[0.0274],
          [0.0154]],

         [[0.0273],
          [0.0154]],

         [[0.0276],
          [0.0155]],

         [[0.0278],
          [0.0157]],

         [[0.0281],
          [0.0158]],

         [[0.0277],
          [0.0155]],

         [[0.0272],
          [0.0152]],

         [[0.0260],
          [0.0146]],

         [[0.0249],
          [0.0139]],

         [[0.0226],
          [0.0126]],

         [[0.0199],
          [0.0110]]],


        [[[0.0200],
          [0.0111]],

         [[0.0217],
          [0.0120]],

         [[0.0237],
          [0.0131]],

         [[0.0240],
          [0.0134]],

         [[0.0273],
          [0.0152]],

         [[0.0278],
          [0.0154]],

         [[0.0284],
          [0.0158]],

         [[0.0283],
          [0.0157]],

         [[0.0286],
          [0.0159]],

         [[0.0289],
          [0.0160]],

         [[0.0291],
          [0.0161]],

         [[0.0286],
          [0.0159]],

         [[0.0281],
          [0.0156]],

         [[0.0269],
          [0.0149]],

         [[0.0258],
          [0.0142]],

         [[0.0234],
          [0.0129]],

         [[0.0206],
          [0.0113]]],


        [[[0.0202],
          [0.0108]],

         [[0.0220],
          [0.0117]],

         [[0.0240],
          [0.0128]],

         [[0.0244],
          [0.0130]],

         [[0.0277],
          [0.0148]],

         [[0.0282],
          [0.0150]],

         [[0.0288],
          [0.0154]],

         [[0.0287],
          [0.0153]],

         [[0.0290],
          [0.0155]],

         [[0.0293],
          [0.0156]],

         [[0.0295],
          [0.0157]],

         [[0.0290],
          [0.0155]],

         [[0.0285],
          [0.0152]],

         [[0.0273],
          [0.0145]],

         [[0.0262],
          [0.0139]],

         [[0.0237],
          [0.0126]],

         [[0.0209],
          [0.0110]]],


        [[[0.0211],
          [0.0109]],

         [[0.0230],
          [0.0118]],

         [[0.0250],
          [0.0129]],

         [[0.0254],
          [0.0131]],

         [[0.0289],
          [0.0149]],

         [[0.0294],
          [0.0152]],

         [[0.0300],
          [0.0155]],

         [[0.0299],
          [0.0155]],

         [[0.0303],
          [0.0156]],

         [[0.0306],
          [0.0157]],

         [[0.0307],
          [0.0158]],

         [[0.0303],
          [0.0156]],

         [[0.0298],
          [0.0153]],

         [[0.0285],
          [0.0146]],

         [[0.0273],
          [0.0140]],

         [[0.0248],
          [0.0127]],

         [[0.0218],
          [0.0111]]],


        [[[0.0226],
          [0.0102]],

         [[0.0246],
          [0.0111]],

         [[0.0268],
          [0.0121]],

         [[0.0272],
          [0.0123]],

         [[0.0310],
          [0.0139]],

         [[0.0315],
          [0.0142]],

         [[0.0322],
          [0.0145]],

         [[0.0321],
          [0.0145]],

         [[0.0325],
          [0.0146]],

         [[0.0327],
          [0.0147]],

         [[0.0329],
          [0.0148]],

         [[0.0324],
          [0.0146]],

         [[0.0318],
          [0.0143]],

         [[0.0305],
          [0.0137]],

         [[0.0292],
          [0.0131]],

         [[0.0265],
          [0.0118]],

         [[0.0233],
          [0.0104]]],


        [[[0.0224],
          [0.0095]],

         [[0.0244],
          [0.0103]],

         [[0.0265],
          [0.0112]],

         [[0.0270],
          [0.0114]],

         [[0.0307],
          [0.0130]],

         [[0.0312],
          [0.0132]],

         [[0.0320],
          [0.0135]],

         [[0.0319],
          [0.0135]],

         [[0.0322],
          [0.0136]],

         [[0.0325],
          [0.0137]],

         [[0.0327],
          [0.0138]],

         [[0.0323],
          [0.0136]],

         [[0.0317],
          [0.0133]],

         [[0.0303],
          [0.0128]],

         [[0.0291],
          [0.0122]],

         [[0.0264],
          [0.0110]],

         [[0.0232],
          [0.0097]]],


        [[[0.0218],
          [0.0091]],

         [[0.0237],
          [0.0099]],

         [[0.0258],
          [0.0108]],

         [[0.0263],
          [0.0110]],

         [[0.0299],
          [0.0125]],

         [[0.0304],
          [0.0127]],

         [[0.0311],
          [0.0130]],

         [[0.0310],
          [0.0129]],

         [[0.0314],
          [0.0131]],

         [[0.0317],
          [0.0132]],

         [[0.0319],
          [0.0133]],

         [[0.0314],
          [0.0131]],

         [[0.0308],
          [0.0128]],

         [[0.0295],
          [0.0123]],

         [[0.0283],
          [0.0117]],

         [[0.0257],
          [0.0106]],

         [[0.0225],
          [0.0093]]],


        [[[0.0220],
          [0.0095]],

         [[0.0240],
          [0.0104]],

         [[0.0261],
          [0.0113]],

         [[0.0265],
          [0.0115]],

         [[0.0302],
          [0.0131]],

         [[0.0307],
          [0.0133]],

         [[0.0314],
          [0.0136]],

         [[0.0313],
          [0.0136]],

         [[0.0317],
          [0.0137]],

         [[0.0320],
          [0.0138]],

         [[0.0322],
          [0.0139]],

         [[0.0317],
          [0.0137]],

         [[0.0311],
          [0.0134]],

         [[0.0298],
          [0.0129]],

         [[0.0286],
          [0.0123]],

         [[0.0259],
          [0.0111]],

         [[0.0228],
          [0.0097]]],


        [[[0.0242],
          [0.0091]],

         [[0.0263],
          [0.0099]],

         [[0.0287],
          [0.0108]],

         [[0.0292],
          [0.0110]],

         [[0.0332],
          [0.0125]],

         [[0.0337],
          [0.0127]],

         [[0.0345],
          [0.0130]],

         [[0.0344],
          [0.0129]],

         [[0.0348],
          [0.0131]],

         [[0.0351],
          [0.0132]],

         [[0.0353],
          [0.0133]],

         [[0.0348],
          [0.0131]],

         [[0.0342],
          [0.0128]],

         [[0.0327],
          [0.0123]],

         [[0.0314],
          [0.0117]],

         [[0.0285],
          [0.0106]],

         [[0.0250],
          [0.0093]]],


        [[[0.0254],
          [0.0087]],

         [[0.0276],
          [0.0095]],

         [[0.0301],
          [0.0103]],

         [[0.0306],
          [0.0105]],

         [[0.0347],
          [0.0119]],

         [[0.0354],
          [0.0121]],

         [[0.0361],
          [0.0124]],

         [[0.0360],
          [0.0124]],

         [[0.0365],
          [0.0125]],

         [[0.0368],
          [0.0126]],

         [[0.0371],
          [0.0127]],

         [[0.0365],
          [0.0125]],

         [[0.0359],
          [0.0123]],

         [[0.0344],
          [0.0117]],

         [[0.0329],
          [0.0112]],

         [[0.0298],
          [0.0101]],

         [[0.0262],
          [0.0089]]],


        [[[0.0243],
          [0.0085]],

         [[0.0264],
          [0.0092]],

         [[0.0288],
          [0.0101]],

         [[0.0293],
          [0.0103]],

         [[0.0333],
          [0.0116]],

         [[0.0339],
          [0.0118]],

         [[0.0347],
          [0.0121]],

         [[0.0346],
          [0.0121]],

         [[0.0350],
          [0.0122]],

         [[0.0353],
          [0.0123]],

         [[0.0356],
          [0.0124]],

         [[0.0351],
          [0.0122]],

         [[0.0345],
          [0.0120]],

         [[0.0330],
          [0.0114]],

         [[0.0316],
          [0.0109]],

         [[0.0287],
          [0.0099]],

         [[0.0252],
          [0.0087]]],


        [[[0.0234],
          [0.0083]],

         [[0.0255],
          [0.0090]],

         [[0.0277],
          [0.0098]],

         [[0.0282],
          [0.0100]],

         [[0.0321],
          [0.0113]],

         [[0.0327],
          [0.0115]],

         [[0.0334],
          [0.0118]],

         [[0.0333],
          [0.0117]],

         [[0.0337],
          [0.0119]],

         [[0.0340],
          [0.0119]],

         [[0.0343],
          [0.0120]],

         [[0.0338],
          [0.0118]],

         [[0.0332],
          [0.0116]],

         [[0.0318],
          [0.0111]],

         [[0.0305],
          [0.0106]],

         [[0.0276],
          [0.0096]],

         [[0.0242],
          [0.0084]]],


        [[[0.0223],
          [0.0084]],

         [[0.0243],
          [0.0091]],

         [[0.0265],
          [0.0099]],

         [[0.0269],
          [0.0101]],

         [[0.0306],
          [0.0114]],

         [[0.0312],
          [0.0116]],

         [[0.0319],
          [0.0119]],

         [[0.0317],
          [0.0119]],

         [[0.0321],
          [0.0120]],

         [[0.0324],
          [0.0121]],

         [[0.0326],
          [0.0122]],

         [[0.0321],
          [0.0120]],

         [[0.0316],
          [0.0118]],

         [[0.0302],
          [0.0112]],

         [[0.0290],
          [0.0107]],

         [[0.0263],
          [0.0097]],

         [[0.0231],
          [0.0085]]],


        [[[0.0214],
          [0.0073]],

         [[0.0233],
          [0.0080]],

         [[0.0254],
          [0.0087]],

         [[0.0258],
          [0.0088]],

         [[0.0293],
          [0.0100]],

         [[0.0298],
          [0.0102]],

         [[0.0305],
          [0.0104]],

         [[0.0304],
          [0.0104]],

         [[0.0307],
          [0.0105]],

         [[0.0310],
          [0.0106]],

         [[0.0312],
          [0.0106]],

         [[0.0308],
          [0.0105]],

         [[0.0302],
          [0.0103]],

         [[0.0290],
          [0.0098]],

         [[0.0278],
          [0.0094]],

         [[0.0252],
          [0.0085]],

         [[0.0221],
          [0.0074]]],


        [[[0.0201],
          [0.0069]],

         [[0.0219],
          [0.0075]],

         [[0.0238],
          [0.0082]],

         [[0.0242],
          [0.0083]],

         [[0.0275],
          [0.0094]],

         [[0.0280],
          [0.0096]],

         [[0.0286],
          [0.0098]],

         [[0.0285],
          [0.0098]],

         [[0.0289],
          [0.0099]],

         [[0.0291],
          [0.0100]],

         [[0.0293],
          [0.0100]],

         [[0.0289],
          [0.0099]],

         [[0.0284],
          [0.0097]],

         [[0.0272],
          [0.0093]],

         [[0.0260],
          [0.0088]],

         [[0.0236],
          [0.0080]],

         [[0.0207],
          [0.0070]]],


        [[[0.0181],
          [0.0057]],

         [[0.0197],
          [0.0062]],

         [[0.0214],
          [0.0067]],

         [[0.0218],
          [0.0069]],

         [[0.0248],
          [0.0078]],

         [[0.0253],
          [0.0079]],

         [[0.0258],
          [0.0081]],

         [[0.0258],
          [0.0081]],

         [[0.0261],
          [0.0082]],

         [[0.0263],
          [0.0082]],

         [[0.0265],
          [0.0083]],

         [[0.0261],
          [0.0081]],

         [[0.0256],
          [0.0080]],

         [[0.0246],
          [0.0076]],

         [[0.0235],
          [0.0073]],

         [[0.0213],
          [0.0066]],

         [[0.0187],
          [0.0058]]]]

In [2]:
scores.shape

AttributeError: 'list' object has no attribute 'shape'

In [3]:
import torch

In [4]:
scores = torch.FloatTensor(scores)

In [5]:
scores.shape

torch.Size([17, 17, 2, 1])

In [6]:
mask = [[[False],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True]],

        [[False],
         [False],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True]],

        [[False],
         [False],
         [False],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True]],

        [[False],
         [False],
         [False],
         [False],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True]],

        [[False],
         [False],
         [False],
         [False],
         [False],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True]],

        [[False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True]],

        [[False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True]],

        [[False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True]],

        [[False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True]],

        [[False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True]],

        [[False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True]],

        [[False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [ True],
         [ True],
         [ True],
         [ True],
         [ True]],

        [[False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [ True],
         [ True],
         [ True],
         [ True]],

        [[False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [ True],
         [ True],
         [ True]],

        [[False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [ True],
         [ True]],

        [[False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [ True]],

        [[False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False],
         [False]]]

In [7]:
torch.gt(mask,0)

TypeError: gt() received an invalid combination of arguments - got (list, int), but expected one of:
 * (Tensor input, Tensor other, *, Tensor out)
 * (Tensor input, Number other, *, Tensor out)


In [9]:
mask = torch.as_tensor(mask)
print(scores.shape)
print(mask.shape)

torch.Size([17, 17, 2, 1])
torch.Size([17, 17, 1])


In [10]:
s = torch.full_like(scores[:, :, 0], float('-inf'))

In [11]:
s.shape

torch.Size([17, 17, 1])

In [14]:
seq_len = 17
n_labels = 2

In [15]:
for i in range(seq_len):
    s[i,i,:] = 0.0

In [19]:
mask.diagonal(offset)

NameError: name 'offset' is not defined

In [17]:
s.view(17,17)

tensor([[0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, 0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, 0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, 0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, 0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf, 0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf, -inf, 0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf, -inf, -inf, 0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, 0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [-

In [25]:
d = 2
offset = d - 1
# n is from seq_len-1 to 0
n = seq_len - offset
diag_mask = mask.diagonal(offset)
# [batch_size, n]
diag_mask.shape

torch.Size([1, 16])